apiVersion: apps/v1

kind: Deployment

metadata:
    name: my-apache-deployment
spec:
    replicas:
    template:
      metadata:
        labels:
          app: my-apache
          
spec:
   containers:
   - name: my-apache-container1
     image: httpd
     ports:
     -  conatinerPort: 80
         
   
